<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Controllers\AccountController.cs\**" />
    <Content Remove="Controllers\AccountController.cs\**" />
    <EmbeddedResource Remove="Controllers\AccountController.cs\**" />
    <None Remove="Controllers\AccountController.cs\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
    <PackageReference Include="Swashbuckle.AspNetCore.Annotations" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BankApp.Services\BankApp.Services.csproj" />
    <ProjectReference Include="..\BankApp.Shared\BankApp.Shared.csproj" />
  </ItemGroup>

</Project>
